### ISSUE TITLE
Does this work on AS 3.5.3

### ISSUE THREAD

**Issue by justdan0227** [underwindfall/NFCAndroid#2]
Trying this out on AS 3.5.3 and getting a build error: 

Could not find org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.3.21.
Required by:
    project :buildSrc
Search in build.gradle files

**Comment by underwindfall** [comment]
build.gradle.kts should contain

```kotlin
plugins {
    `kotlin-dsl`
}
// Required since Gradle 4.10+.
repositories {
    jcenter()
}
```
The **kotlin-dsl** plugin now requires a repository to be declared

With Kotlin 1.2.60, the Kotlin Gradle Plugin driving the kotlin compiler requires extra dependencies that aren't required by Gradle Kotlin DSL scripts alone and aren't embedded into Gradle.

This can be fixed by adding a repository that contains Kotlin compiler dependencies on the project where the kotlin-dsl plugin is applied: repositories { jcenter() }


====================================

It's been fixed.
